# ==========================================================
# 📡 AIT Brainlab - Ansible Day 1 Operations Inventory
# ==========================================================

[mgmt]
brainlab-mgmt-vm ansible_host=brainlab-mgmt-vm ansible_user=akraradets ansible_ssh_private_key_file=~/.ssh/google_compute_engine ansible_ssh_common_args='-o ProxyCommand="gcloud compute start-iap-tunnel %h %p --listen-on-stdin --zone=asia-southeast1-a --project=ait-brainlab-mgmt"'

[storage]
# TrueNAS Core / Scale NFS Storage Node
cairo ansible_host=cairo

[servers]
# Physical GPU Compute Nodes
la ansible_host=la.cs.ait.ac.th
tokyo ansible_host=tokyo.cs.ait.ac.th

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
netbird_management_url=https://netbird2.brain.cs.ait.ac.th
netbird_version=0.77.0
