# ==========================================================
# 📡 AIT Brainlab - Ansible Day 1 Operations Inventory
# ==========================================================

[gcp-mgmt]
brainlab-mgmt-vm

[onprem-truenas]
cairo ansible_host=cairo

[onprem-ubuntu-server]
la ansible_host=la.cs.ait.ac.th
tokyo ansible_host=tokyo.cs.ait.ac.th
