---
# ==========================================================
# 🌐 Global Variables (Inherited by all hosts)
# ==========================================================
ansible_user: root
ansible_python_interpreter: /usr/bin/python3
netbird_management_url: https://netbird.brain.cs.ait.ac.th
netbird_version: "0.77.0"
