FROM jupyterhub/jupyterhub:5.2.1

# Install DockerSpawner, Google Authenticator, and LDAP3 library
RUN pip install --no-cache-dir \
    dockerspawner==13.0.0 \
    oauthenticator==17.3.0 \
    ldap3==2.9.1
